// flow-typed signature: 58ee248a6817f0c4e4d193f18f7b5774
// flow-typed version: <<STUB>>/typedef-converter_v^0.1.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typedef-converter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "typedef-converter" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "typedef-converter/lib/index" {
  declare module.exports: any;
}

declare module "typedef-converter/lib/nodeName" {
  declare module.exports: any;
}

declare module "typedef-converter/lib/parser" {
  declare module.exports: any;
}

declare module "typedef-converter/lib/printer" {
  declare module.exports: any;
}

declare module "typedef-converter/lib/tree" {
  declare module.exports: any;
}

// Filename aliases
declare module "typedef-converter/lib/index.js" {
  declare module.exports: $Exports<'typedef-converter/lib/index'>;
}
declare module "typedef-converter/lib/nodeName.js" {
  declare module.exports: $Exports<'typedef-converter/lib/nodeName'>;
}
declare module "typedef-converter/lib/parser.js" {
  declare module.exports: $Exports<'typedef-converter/lib/parser'>;
}
declare module "typedef-converter/lib/printer.js" {
  declare module.exports: $Exports<'typedef-converter/lib/printer'>;
}
declare module "typedef-converter/lib/tree.js" {
  declare module.exports: $Exports<'typedef-converter/lib/tree'>;
}
