// flow-typed signature: 3b7b3f6deb22bcaf364ac8ab632a97a6
// flow-typed version: <<STUB>>/xls-to-json_v^0.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xls-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "xls-to-json" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "xls-to-json/libs/index" {
  declare module.exports: any;
}

declare module "xls-to-json/sample/sample" {
  declare module.exports: any;
}

declare module "xls-to-json/test/xls2json.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "xls-to-json/index" {
  declare module.exports: $Exports<'xls-to-json'>;
}
declare module "xls-to-json/index.js" {
  declare module.exports: $Exports<'xls-to-json'>;
}
declare module "xls-to-json/libs/index.js" {
  declare module.exports: $Exports<'xls-to-json/libs/index'>;
}
declare module "xls-to-json/sample/sample.js" {
  declare module.exports: $Exports<'xls-to-json/sample/sample'>;
}
declare module "xls-to-json/test/xls2json.test.js" {
  declare module.exports: $Exports<'xls-to-json/test/xls2json.test'>;
}
